trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm ci
  workingDirectory: 'api'
  displayName: 'Install API dependencies'

- script: |
    npm run build
  displayName: 'Build Next.js app'
  env:
    DI_ENDPOINT: $(DI_ENDPOINT)
    DI_KEY: $(DI_KEY)

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    api_location: 'api'
    output_location: 'out'
    azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
  env:
    DI_ENDPOINT: $(DI_ENDPOINT)
    DI_KEY: $(DI_KEY)